;;;; transform.lisp — VP8 inverse transforms (IDCT & IWHT), RFC 6386 §14.3
(in-package #:reel.decode)

(defun vp8-idct (ip)
  "Inverse DCT (RFC 6386 §14.3).  Returns a fresh 16-element fixnum array."
  (declare (type (simple-array fixnum (16)) ip))
  (let ((tmp (make-array 16 :element-type 'fixnum))
        (op (make-array 16 :element-type 'fixnum)))
    (declare (type (simple-array fixnum (16)) tmp op))
    ;; columns, stride 4
    (dotimes (i 4)
      (let* ((a1 (+ (aref ip i) (aref ip (+ 8 i))))
             (b1 (- (aref ip i) (aref ip (+ 8 i))))
             (t1 (ash (* (aref ip (+ 4 i)) 35468) -16))
             (t2 (+ (aref ip (+ 12 i)) (ash (* (aref ip (+ 12 i)) 20091) -16)))
             (c1 (- t1 t2))
             (t1 (+ (aref ip (+ 4 i)) (ash (* (aref ip (+ 4 i)) 20091) -16)))
             (t2 (ash (* (aref ip (+ 12 i)) 35468) -16))
             (d1 (+ t1 t2)))
        (setf (aref tmp i) (+ a1 d1)
              (aref tmp (+ 12 i)) (- a1 d1)
              (aref tmp (+ 4 i)) (+ b1 c1)
              (aref tmp (+ 8 i)) (- b1 c1))))
    ;; rows
    (dotimes (i 4)
      (let* ((b (* 4 i))
             (a1 (+ (aref tmp b) (aref tmp (+ b 2))))
             (b1 (- (aref tmp b) (aref tmp (+ b 2))))
             (t1 (ash (* (aref tmp (+ b 1)) 35468) -16))
             (t2 (+ (aref tmp (+ b 3)) (ash (* (aref tmp (+ b 3)) 20091) -16)))
             (c1 (- t1 t2))
             (t1 (+ (aref tmp (+ b 1)) (ash (* (aref tmp (+ b 1)) 20091) -16)))
             (t2 (ash (* (aref tmp (+ b 3)) 35468) -16))
             (d1 (+ t1 t2)))
        (setf (aref op b) (ash (+ a1 d1 4) -3)
              (aref op (+ b 3)) (ash (+ (- a1 d1) 4) -3)
              (aref op (+ b 1)) (ash (+ b1 c1 4) -3)
              (aref op (+ b 2)) (ash (+ (- b1 c1) 4) -3))))
    op))

(defun vp8-iwht (ip)
  "Inverse Walsh-Hadamard transform (RFC 6386 §14.3).  Returns a fresh 16-element fixnum array."
  (declare (type (simple-array fixnum (16)) ip))
  (let ((tmp (make-array 16 :element-type 'fixnum))
        (op (make-array 16 :element-type 'fixnum)))
    (declare (type (simple-array fixnum (16)) tmp op))
    ;; stride 4
    (dotimes (i 4)
      (let* ((a1 (+ (aref ip i) (aref ip (+ 12 i))))
             (b1 (+ (aref ip (+ 4 i)) (aref ip (+ 8 i))))
             (c1 (- (aref ip (+ 4 i)) (aref ip (+ 8 i))))
             (d1 (- (aref ip i) (aref ip (+ 12 i)))))
        (setf (aref tmp i) (+ a1 b1)
              (aref tmp (+ 4 i)) (+ c1 d1)
              (aref tmp (+ 8 i)) (- a1 b1)
              (aref tmp (+ 12 i)) (- d1 c1))))
    ;; rows
    (dotimes (i 4)
      (let* ((b (* 4 i))
             (a1 (+ (aref tmp b) (aref tmp (+ b 3))))
             (b1 (+ (aref tmp (+ b 1)) (aref tmp (+ b 2))))
             (c1 (- (aref tmp (+ b 1)) (aref tmp (+ b 2))))
             (d1 (- (aref tmp b) (aref tmp (+ b 3)))))
        (setf (aref op b) (ash (+ a1 b1 3) -3)
              (aref op (+ b 1)) (ash (+ c1 d1 3) -3)
              (aref op (+ b 2)) (ash (+ (- a1 b1) 3) -3)
              (aref op (+ b 3)) (ash (+ (- d1 c1) 3) -3))))
    op))